language: scala
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    $HOME/.ivy2
    regression/install
    chisel/target
    context-dependent-environments/target
    groundtest/target
    hardfloat/target
    junctions/target
    project/project/target
    project/target
    rocket/target
    target
    uncore/target
    zscale/target
    xfiles-dana/tests/install
    xfiles-dana/target
    xfiles-dana/project/target

# packages needed to build riscv-tools
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - dc
      - python-numpy
      - python-matplotlib

env:
  global:
    - ROCKETCHIP_ADDONS=xfiles-dana
    - PATH=$PATH:$XFILES/usr/bin
  matrix:
    - PES=4 EPB=4
    - PES=8 EPB=8
    - PES=16 EPB=16
    - PES=32 EPB=32

# blacklist private branches
branches:
  except:
    - hwacha
    - boom
    - hurricane

before_install:
  - rm riscv-tools/.travis.yml
  - export CXX=g++-4.8 CC=gcc-4.8
  - export CPP_CONFIG=XFilesDanaCppPe$PES\Epb$EPB\Config

script:
  - cd xfiles-dana/tests
  - ./regress.sh

before_cache:
  - ls -tr regression/install | tail -n+2 | sed s@^@regression/install/@ | xargs rm -rf
